### ISSUE TITLE
似乎不工作（）

### ISSUE THREAD

**Issue by citydirector** [MeetWq/nonebot-plugin-chess#2]
![image](https://user-images.githubusercontent.com/45933075/159240420-c7d264f4-4d06-4c5d-9759-6c0db929ab47.png)

**Comment by MeetWq** [comment]
这个需要两个人下，所以只能在群里用

**Comment by citydirector** [comment]
ok，能正常工作，是我的疏忽（）
另外，能否增加一个白名单？就是只响应相应的群的消息

**Comment by MeetWq** [comment]
白名单可以试试插件管理器 [nonebot-plugin-manager](https://github.com/nonepkg/nonebot-plugin-manager)

**Comment by citydirector** [comment]
非常感谢！
